import type { Course } from "../types";

const course: Course = {
  slug: "react-essentials",
  level: "intermediate",
  durationMinutes: 360,
  accentColor: "#61dafb",
  coverGradient: "from-cyan-400 via-sky-500 to-blue-600",
  icon: "Atom",
  category: "programming",
  en: { title: "React Essentials", tagline: "Build modern interactive UIs with components.", description: "Curated from freeCodeCamp's React courses and Codezilla (Arabic). Components, props, state, hooks, and effects.", learningOutcomes: ["Build component-based UIs", "Manage state with hooks", "Fetch data with useEffect", "Ship a React app"], prerequisites: ["JavaScript fundamentals"] },
  ar: { title: "أساسيات React", tagline: "ابني واجهات تفاعلية حديثة بمكونات.", description: "مختارة من كورسات freeCodeCamp و Codezilla. المكونات، props، state، hooks، و effects.", learningOutcomes: ["ابني واجهات بمكونات", "إدارة state بـhooks", "جلب بيانات بـuseEffect", "اطلق تطبيق React"], prerequisites: ["أساسيات JavaScript"] },
  lessons: [
    { slug: "components-and-jsx", durationMinutes: 40, video: { en: { youtubeId: "bMknfKXIFA8", sourceName: "freeCodeCamp", sourceUrl: "https://www.youtube.com/@freecodecamp" }, ar: { youtubeId: "ZrtgUmGRRBM", sourceName: "Codezilla", sourceUrl: "https://www.youtube.com/@codezilla" } },
      en: { title: "Components & JSX", summary: "The building blocks of React apps.", content: `# Components\n\n\`\`\`jsx\nfunction Greeting({ name }) {\n  return <h1>Hello, {name}!</h1>;\n}\n\`\`\`` },
      ar: { title: "المكونات و JSX", summary: "اللبنات الأساسية لتطبيقات React.", content: `# المكونات\n\n\`\`\`jsx\nfunction Greeting({ name }) {\n  return <h1>Hello, {name}!</h1>;\n}\n\`\`\`` },
      quiz: [{ correctIndex: 0, en: { question: "JSX is...", options: ["A syntax extension that compiles to JS", "A new language", "An HTML template", "A CSS framework"], explanation: "JSX compiles to React.createElement calls." }, ar: { question: "JSX هو...", options: ["امتداد لصيغة JS بيتحوّل لـJS", "لغة جديدة", "قالب HTML", "إطار CSS"], explanation: "JSX بيتحوّل لاستدعاءات React.createElement." } }] },
    { slug: "props-and-state", durationMinutes: 40, en: { title: "Props & useState", summary: "Pass data down, manage local state.", content: `# Props & State\n\n\`\`\`jsx\nconst [count, setCount] = useState(0);\n<button onClick={() => setCount(count + 1)}>{count}</button>\n\`\`\`` }, ar: { title: "Props و useState", summary: "مرر بيانات للأسفل، إدارة الحالة المحلية.", content: `# Props و State\n\n\`\`\`jsx\nconst [count, setCount] = useState(0);\n<button onClick={() => setCount(count + 1)}>{count}</button>\n\`\`\`` }, quiz: [{ correctIndex: 1, en: { question: "useState returns...", options: ["A value only", "[value, setter] tuple", "A setter only", "An object {value, set}"], explanation: "useState returns an array with value and setter." }, ar: { question: "useState بترجع...", options: ["قيمة بس", "[value, setter] tuple", "setter بس", "object {value, set}"], explanation: "useState بترجع array فيه القيمة و الـsetter." } }] },
    { slug: "useeffect-and-fetching", durationMinutes: 45, en: { title: "useEffect & Data Fetching", summary: "Side effects in React.", content: `# useEffect\n\n\`\`\`jsx\nuseEffect(() => {\n  fetch("/api/users").then(r => r.json()).then(setUsers);\n}, []);\n\`\`\`\n\nEmpty dependency array = run once on mount.` }, ar: { title: "useEffect و جلب البيانات", summary: "الـside effects في React.", content: `# useEffect\n\n\`\`\`jsx\nuseEffect(() => {\n  fetch("/api/users").then(r => r.json()).then(setUsers);\n}, []);\n\`\`\`\n\nقائمة dependencies فاضية = يشتغل مرة واحدة عند الـmount.` }, quiz: [{ correctIndex: 2, en: { question: "Empty [] dependency array means...", options: ["Run on every render", "Never run", "Run once on mount", "Run on unmount only"], explanation: "Empty deps run the effect a single time after mount." }, ar: { question: "قائمة dependencies [] فاضية معناها...", options: ["شغّال كل render", "ميشتغلش", "يشتغل مرة واحدة عند mount", "يشتغل عند unmount بس"], explanation: "Empty deps بيشغّل الـeffect مرة واحدة بعد الـmount." } }] },
    { slug: "lists-and-keys", durationMinutes: 35, en: { title: "Lists, Keys & Conditional Rendering", summary: "Render arrays correctly.", content: `# Lists\n\n\`\`\`jsx\n{users.map(u => <UserCard key={u.id} user={u} />)}\n{isLoading ? <Spinner /> : <Data />}\n\`\`\`` }, ar: { title: "Lists و Keys و Conditional Rendering", summary: "اعرض arrays بشكل صحيح.", content: `# Lists\n\n\`\`\`jsx\n{users.map(u => <UserCard key={u.id} user={u} />)}\n{isLoading ? <Spinner /> : <Data />}\n\`\`\`` }, quiz: [{ correctIndex: 1, en: { question: "Why do React lists need a key prop?", options: ["For CSS styling", "To help React identify items efficiently", "It's optional", "Required for animations"], explanation: "Keys help React reconcile DOM updates." }, ar: { question: "ليه lists في React محتاجة key؟", options: ["للتنسيق", "علشان React تميّز العناصر بكفاءة", "اختياري", "إجباري للأنميشن"], explanation: "Keys بتساعد React في تحديث الـDOM." } }] },
  ],
  project: { slug: "weather-react-app", difficulty: "medium", estimatedHours: 6, en: { title: "React Weather App", brief: "Build a React weather app with search, current conditions, and a 5-day forecast.", requirements: ["Functional components + hooks", "Fetch from OpenWeather API", "Loading & error states", "Responsive layout"], deliverables: ["Live URL on Vercel", "GitHub repo"] }, ar: { title: "تطبيق طقس بـReact", brief: "ابني تطبيق طقس بـReact مع بحث، حالة حالية، و توقع 5 أيام.", requirements: ["Functional components + hooks", "Fetch من OpenWeather API", "حالات loading و error", "تصميم متجاوب"], deliverables: ["رابط على Vercel", "GitHub repo"] } },
};

export default course;
