// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdowaletwmqjhvmaervb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkb3dhbGV0d21xamh2bWFlcnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyOTQxMDksImV4cCI6MjA5NDg3MDEwOX0.Q-USlWrKbii6IjYuZWpFnixAEPiRgsxEv3Jm2dcEvcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});